apiVersion: v1
kind: Service
meta:
  name: front-service-v1
spec:
  selector:
    app: nginx-v1
  ports:
  - protocol: TCP # 通信类型（TCP/UDP）
    port: 80 # k8s 容器之间互相访问的端口
    targetPort: 80 # 原本 Pod 开放的端口
  type: NodePort # NodePort，Service的一种访问方式
