apiVersion: apps/v1
kind: Deployment # 声明 Kubernetes 的资源类型
metadata:
  name: front-v1
spec:
  selector:
    matchLabels:
      app: nginx-v1
  replicas: 3
  template: 
    metadata:
      labels: 
        app: nginx-v1
  spec:
    containers:
    - name: nginx
      image: registry.cn-hangzhou.aliyuncs.com/janlay/k8s_test:v1
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-service-v1
spec:
  selector:
    app: nginx-v1
  ports:
  - protocol: TCP # 通信类型（TCP/UDP）
    port: 80 # k8s 容器之间互相访问的端口
    targetPort: 80 # 原本 Pod 开放的端口
  type: NodePort # NodePort，Service的一种访问方式
