apiVersion: apps/v1
kind: Development # 声明 Kubernetes 的资源类型
metadata:
  name: front-v1
spec:
  selector:
    matchLabels:
      app: nginx-v1
  replicas: 3
  template: 
    metadata:
      labels: 
        app: nginx-v1
  spec:
    containers:
    - name: nginx
      image: registry.cn-hangzhou.aliyuncs.com/janlay/k8s_test:v1
      ports:
      - containerPort: 80